export const ENROLLMENT_REPOSITORY = Symbol('ENROLLMENT_REPOSITORY');

export const ENTITLEMENT_REPOSITORY = Symbol('ENTITLEMENT_REPOSITORY');

export const LEARNING_SESSION_REPOSITORY = Symbol(
  'LEARNING_SESSION_REPOSITORY',
);

export const PROGRESS_REPOSITORY = Symbol('PROGRESS_REPOSITORY');
