packages:
  - "apps/*"
  - "libs/*"
  - "libs/shared/*"
  - "tools/*"
  - "api-e2e"

allowBuilds:
  "@parcel/watcher": true
  "less": true
  "nx": true
  "@swc/core": true
  '@prisma/engines': true
  prisma: true
  msgpackr-extract: true
  esbuild: true
